// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNc_ykR9D64eSUT3uzPj9Im-oAHok1sOQ',
    appId: '1:900807584756:web:fb00a09b93f7ba34c867a1',
    messagingSenderId: '900807584756',
    projectId: 'prjpab2-si61-2327240024',
    authDomain: 'prjpab2-si61-2327240024.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240024.firebasestorage.app',
    measurementId: 'G-FYKJZGMKCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hY8NZwSNNseib5a2VDcs91xvNh6jFgQ',
    appId: '1:900807584756:android:60ece6e61451d0d9c867a1',
    messagingSenderId: '900807584756',
    projectId: 'prjpab2-si61-2327240024',
    storageBucket: 'prjpab2-si61-2327240024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXo2MjQHw4CovRFngfl6JaBFhxhtrz11k',
    appId: '1:900807584756:ios:92046cf990efa6f9c867a1',
    messagingSenderId: '900807584756',
    projectId: 'prjpab2-si61-2327240024',
    storageBucket: 'prjpab2-si61-2327240024.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXo2MjQHw4CovRFngfl6JaBFhxhtrz11k',
    appId: '1:900807584756:ios:92046cf990efa6f9c867a1',
    messagingSenderId: '900807584756',
    projectId: 'prjpab2-si61-2327240024',
    storageBucket: 'prjpab2-si61-2327240024.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNc_ykR9D64eSUT3uzPj9Im-oAHok1sOQ',
    appId: '1:900807584756:web:34560e021e7cb971c867a1',
    messagingSenderId: '900807584756',
    projectId: 'prjpab2-si61-2327240024',
    authDomain: 'prjpab2-si61-2327240024.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240024.firebasestorage.app',
    measurementId: 'G-MJN2KH3466',
  );
}
